### ISSUE TITLE
Access to rsim via `std::map::operator[]()` is not guaranteed to be thread safe

### ISSUE THREAD

**Issue by LiKao** [igmmgi/DMCfun#3]
In the simulation code [line 70](https://github.com/igmmgi/DMCfun/blob/7552278280e64dd6880a6307ddb3f5e42991697d/src/runDMC.cpp#L70) the shared map `rsim`  is accessed via `std::map::operator[]`. However, the C++ standard only ensures thread-safety for read operations (i.e. `const` functions) on STL-Containers ([see Section 26.2.2 of the C++17 standard draft version](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf)). 

For associative containers (i.e. `std::map` or `std::unordered_map`), the `operator[]()` is not considered `const` and therefore not thread safe (see the [documentation](https://en.cppreference.com/w/cpp/container/map/operator_at), which does not include a const version of this operator). 

While this may not be an issue, it may lead to data corruption and/or crashes in rare and hard to debug circumstances.

Proposed fix: Use the `std::map::at` function, which is considered `const` for the purpose of Section 26.2.2.

**Comment by igmmgi** [comment]
rsim.at("eq4")[i]

PR?

Thanks

**Comment by LiKao** [comment]
Yes, exactly. Didn't have time to create and test a PR yesterday, sorry.
