### ISSUE TITLE
NA values observed when calling dmcObservedData() 

### ISSUE THREAD

**Issue by HeatherUrry** [igmmgi/DMCfun#5]
Hi @igmmgi,

Terrific package-- thank you for making it.

I was trying it out today and noticed it was throwing an xlim error when trying to plot the output of the `dmcObservedData() ` function, and the `dmcFit()` function threw an error on that output too. 

In backtracing the error, I noticed NA values in $delta and $caf when running `dmcObservedData()` on my data.  This seems to be due to the lines linked below lacking `na.rm = TRUE` in the `summarize()` arguments. After adding `na.rm = TRUE` to both, it seemed to work but I'm unsure about the unintended consequences of doing so! Figured I would put this on your radar in case it's something to address on your end. 

https://github.com/igmmgi/DMCfun/blob/6b01f797b3cf2f13457642862961729ddfe407d9/R/dmcData.R#L369-L400

Best,

Heather

**Comment by igmmgi** [comment]
Hello Heather,

Thanks for the bug report. Are you able to share the data set which produces the NA values? I would like to track where/why these values occur before I add a na.rm = TRUE.

**Comment by HeatherUrry** [comment]
Hi Ian,

I'm attaching a subset of my data, [n50.csv](https://github.com/igmmgi/DMCfun/files/7790883/n50.csv) (n = 50 subjects). You can reproduce the issue by running the following:

```
dat <- read.csv("n50.csv")
datOb <- dmcObservedData(dat)
plot(datOb)
datObFit <- dmcFit(datOb)
```

The plot command produces this error: 

Error in plot.window(...) : need finite 'xlim' values

The dmcFit command produces this error after searching initial parameter gridspace:  

Error in optim(par = as.numeric(startVals[!as.logical(fixedFit)]), fn = minimizeCostValue,  : 
  non-finite value supplied by optim

I then removed subjects with NA values in `$deltaErrorsSubject` and `$deltaSubject` in datOb to see if that corrected the issue:

```
exclude <- unique(c(datOb$deltaErrorsSubject$Subject[ is.na(datOb$deltaErrorsSubject$meanEffect) ],
   datOb$deltaSubject$Subject[ is.na(datOb$deltaSubject$meanEffect) ]))
datOb_excl <- dmcObservedData(subset(dat, !Subject %in% exclude))
plot(datOb_excl)
datOb_exclFit <- dmcFit(datOb_excl)
summary(datOb_exclFit)
plot(datOb_exclFit, datOb_excl)
```

After applying the exclusions, everything worked. 

Last, I used a local version of the `dmcObservedData()` function after adding `na.rm = TRUE` to the lines referenced in my original post. Everything worked without exclusions.

I hope this is helpful!

Heather

**Comment by igmmgi** [comment]
Hello Heather,

Thanks for the data file. This helps a lot! I think the problem is related to Subject 42. This participant does not have any correct trials in the incomp condition.

```R
dat <- read.csv("n50.csv")
table(dat$Subject, dat$Comp, dat$Error)

dat <- dat[dat$Subject != 42, ]

datOb <- dmcObservedData(dat)
plot(datOb)
datObFit <- dmcFit(datOb)
```
This now works. Looking at some of the trial numbers for correct incomp trials, I would recommend reducing the number of delta bins calculated, perhaps to 9.  

```
datOb <- dmcObservedData(dat, nDelta = 9)
plot(datOb)
datObFit <- dmcFit(datOb, nDelta = 9)
```
In the next version I will add some code checks to catch this issue and give a better error message!

Thanks,
Ian.

**Comment by HeatherUrry** [comment]
Thanks, Ian! 

Yes, before uploading the data for n = 50, I identified four subjects in my full dataset who had accuracy of 0 for the incomp condition but excluding just them doesn't fix the issue, even with a lower nDelta. However, excluding based on an overall accuracy criterion of <= .544* across the two conditions does. That criterion eliminates the four subjects with accuracy of 0 for the incomp condition plus a bunch of subjects with low but not zero overall accuracy. This supports your suggestion that some subjects were contributing too few trials to fill out all the delta bins. 

A code check for low accuracy within and across conditions would be cool, as would an input argument option to specify an overall accuracy cut-off (like how it's possible to indicate a range of acceptable RTs using the outlier argument). 

I guess in the end it's best not to add `na.rm = TRUE` in the places noted before because doing so would enable the model to estimate parameters based on unreliable delta in some/all bins for some subjects.

Thanks again! 

Heather

* .544 is oddly specific but it's the overall accuracy value at which the cumulative probability of chance performance is 0.046.
